### ISSUE TITLE
Tips: improve your score

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/scrt-network-oracle-client#14]
### Description
A clickable pop-up window with static tips on best practices to improve your credit score

### Tasks
 - [ ] generate pop-up window
 - [ ] include static tips (see Slack)
 - [ ] (optional) dynamically display Plaid OR Coinbase tips depending on what validator the user chose
